name: Tests

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7] #[3.5, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, windows-latest, macos-latest]
      #fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} (Miniconda)
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
    - name: Install build dependencies
      shell: bash -l {0}
      run: conda install -n base anaconda-client conda-build conda-verify numpy
    - name: Build
      shell: bash -l {0}
      run: conda build recipe
    - name: Install test dependencies
      shell: bash -l {0}
      run: |
        conda install -q pytest pylint pytest-pylint toml pytest-cov codecov cython
        conda install pyteomics -c bioconda
    - name: Install xvfb
      shell: bash -l {0}
      run: conda install pytest-xvfb
      if: runner.os == 'Linux'
    - name: Install built package
      shell: bash -l {0}
      run: conda install --use-local libmetgem
    - name: Test with pytest
      shell: bash -l {0}
      run: cd tests && pytest --cov=libmetgem
    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./tests/coverage.xml
        name: ${{ runner.os }} Python ${{ matrix.python-version }}
